# dashboard_application/ids.py
# EOTS v2.5 - CANONICAL COMPONENT IDENTIFIERS (AUTHORITATIVE)

"""
Defines constant IDs for Dash components used throughout the EOTS dashboard application.
Centralizing IDs here prevents typos and simplifies component management across modules.
"""

# --- Core Application & State Management ---
ID_URL_LOCATION = "url-location-id"
ID_MAIN_DATA_STORE = "main-data-store-id"
ID_INTERVAL_LIVE_UPDATE = "interval-live-update-id"
ID_MANUAL_REFRESH_BUTTON = "manual-refresh-button-id"

# --- Layout Containers ---
ID_PAGE_CONTENT = "page-content-id"
ID_STATUS_ALERT_CONTAINER = "status-alert-container-id"
ID_MASTER_HEADER = "master-header-id"

# --- Control Panel (in Header) ---
ID_SYMBOL_INPUT = "symbol-input-id"
ID_REFRESH_INTERVAL_DROPDOWN = "refresh-interval-dropdown-id"

# --- Main Dashboard Mode (Example Specific IDs) ---
# These are generated by main_dashboard_display.py
ID_REGIME_DISPLAY_CARD = "regime-display-card-id"
ID_VAPI_GAUGE = "vapi-gauge-id"
ID_DWFD_GAUGE = "dwfd-gauge-id"
ID_TW_LAF_GAUGE = "tw-laf-gauge-id"
ID_RECOMMENDATIONS_TABLE = "recommendations-table-id"